accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.loginview,name='login'),
    path('register/',views.register,name='register'),
]

ecommerse/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.store,name='store'),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name='checkout'),
    path('gotoCart/',views.gotoCart,name='gotoCart'),
    path('updatecart/',views.updatecart,name='updatecart'),
    path('gotocheckout/',views.gotocheckout,name='gotocheckout'),
    path('complete/',views.complete,name='complete'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
import email
from django import forms
from store.models import Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError 



class CreateUserForm(UserCreationForm):
    email = forms.EmailField()
    name = forms.CharField()
    class Meta:
        model = Customer
        fields = ['name','email','password1','password2']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control',}),
            'password1':forms.PasswordInput(attrs={'class':'form-control',}),
            'password2':forms.PasswordInput(attrs={'class':'form-control',})
        }
    def name_clean(self):  
        name = self.cleaned_data['name'].lower()  
        new = User.objects.filter(username = name)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return name  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError(" Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['name'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user  

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from store.models import Customer
from .forms import CreateUserForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from random import randint




# Create your views here.



def register(request):
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        name = request.POST['name']
        username=to_username(name)
        if User.objects.filter(email=email).exists():
            return render(request,'accounts/register.html')
        if password1==password2 and password1 and name and email:
            user = User.objects.create_user(username,email,password1)
            customer = Customer.objects.create(user=user,name=name)
            customer.save()
            login(request,user)
            return redirect('/')
            # else:
            #     raise ValidationError('Password doesn\'t match')
    return render(request,'accounts/register.html')


def loginview(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email)
        print(password)
        if User.objects.filter(email=email).exists():
            customeruser = User.objects.get(email=email)
            user = authenticate(request,username=customeruser.username,password=password)
            if user is not None:
                login(request,user)
                return redirect('/')
            
        
        # user = authenticate(request,email=email,password=password)
        
            
    return render(request,'accounts/login.html')


def to_username(s):
    parts = s.lower().split()
    username = ''
    for item in parts:
        username+=item
    while User.objects.filter(username=username).exists():
        username+=str(randint(0,10))
    return username

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <style>
      a{
        text-decoration: none;
      }
    </style>
</head>
<body>

    <div class="container mt-3">
      <form method="POST" >
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail">Email</label>
          <input type="email" class="form-control" id="id_username" placeholder="Email" name="email">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="id_email" placeholder="Password" name="password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Sign in</button>
        <br><br>
        <p>Don't have an account? <a href="{% url 'accounts:register' %}">Register</a></p>
      </form>     
    </div>

</body>

templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <style>
      a{
        text-decoration: none;
      }
    </style>
</head>
<body>
    <div class="container mt-3">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputName">Name</label>
            <input type="text" class="form-control" id="id_username" placeholder="Name" name="name">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputEmail">Email address</label>
          <input type="email" class="form-control" id="id_email" placeholder="Enter email" name="email">
        </div>
        <br>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="id_password1" placeholder="Password" name="password1">
        </div>
        <br>
        <div class="form-group">
            <label for="exampleInputPassword2">Repeat Password</label>
            <input type="password" class="form-control" id="id_password1" placeholder="Password again" name="password2">
          </div>
          <br>  
        <button type="submit" class="btn btn-primary">Sign up</button>
        <br>
        <p>Already have an account? <a href="{% url 'accounts:login' %}">Sign in</a></p>
    </form>
    </div>
</body>
</html>